//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "combineddevicepartpinsourceinfo")
public class Combineddevicepartpinsourceinfo {

    @XmlAttribute(name = "generatedid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String generatedid;
    @XmlAttribute(name = "sourcepintype", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sourcepintype;
    @XmlAttribute(name = "sourcepinbaseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sourcepinbaseid;
    @XmlAttribute(name = "sourcepinid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sourcepinid;
    @XmlAttribute(name = "slotdevicebaseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String slotdevicebaseid;
    @XmlAttribute(name = "slotdeviceid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String slotdeviceid;

    /**
     * Gets the value of the generatedid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratedid() {
        return generatedid;
    }

    /**
     * Sets the value of the generatedid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratedid(String value) {
        this.generatedid = value;
    }

    /**
     * Gets the value of the sourcepintype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcepintype() {
        return sourcepintype;
    }

    /**
     * Sets the value of the sourcepintype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcepintype(String value) {
        this.sourcepintype = value;
    }

    /**
     * Gets the value of the sourcepinbaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcepinbaseid() {
        return sourcepinbaseid;
    }

    /**
     * Sets the value of the sourcepinbaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcepinbaseid(String value) {
        this.sourcepinbaseid = value;
    }

    /**
     * Gets the value of the sourcepinid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcepinid() {
        return sourcepinid;
    }

    /**
     * Sets the value of the sourcepinid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcepinid(String value) {
        this.sourcepinid = value;
    }

    /**
     * Gets the value of the slotdevicebaseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlotdevicebaseid() {
        return slotdevicebaseid;
    }

    /**
     * Sets the value of the slotdevicebaseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlotdevicebaseid(String value) {
        this.slotdevicebaseid = value;
    }

    /**
     * Gets the value of the slotdeviceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSlotdeviceid() {
        return slotdeviceid;
    }

    /**
     * Sets the value of the slotdeviceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSlotdeviceid(String value) {
        this.slotdeviceid = value;
    }

}
