//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "constraintdefinedvalueof")
public class Constraintdefinedvalueof {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "elementref", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String elementref;
    @XmlAttribute(name = "valueof", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String valueof;
    @XmlAttribute(name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the elementref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementref() {
        return elementref;
    }

    /**
     * Sets the value of the elementref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementref(String value) {
        this.elementref = value;
    }

    /**
     * Gets the value of the valueof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueof() {
        return valueof;
    }

    /**
     * Sets the value of the valueof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueof(String value) {
        this.valueof = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "literal";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
