//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "sourceinterconnect")
public class Sourceinterconnect {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "refid", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String refid;
    @XmlAttribute(name = "sourcediagramname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sourcediagramname;
    @XmlAttribute(name = "harness")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String harness;
    @XmlAttribute(name = "connrefid1", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connrefid1;
    @XmlAttribute(name = "connrefid2", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String connrefid2;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the refid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefid() {
        return refid;
    }

    /**
     * Sets the value of the refid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefid(String value) {
        this.refid = value;
    }

    /**
     * Gets the value of the sourcediagramname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcediagramname() {
        return sourcediagramname;
    }

    /**
     * Sets the value of the sourcediagramname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcediagramname(String value) {
        this.sourcediagramname = value;
    }

    /**
     * Gets the value of the harness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarness() {
        return harness;
    }

    /**
     * Sets the value of the harness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarness(String value) {
        this.harness = value;
    }

    /**
     * Gets the value of the connrefid1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnrefid1() {
        return connrefid1;
    }

    /**
     * Sets the value of the connrefid1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnrefid1(String value) {
        this.connrefid1 = value;
    }

    /**
     * Gets the value of the connrefid2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnrefid2() {
        return connrefid2;
    }

    /**
     * Sets the value of the connrefid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnrefid2(String value) {
        this.connrefid2 = value;
    }

}
