//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerrow",
    "decorationpropertycomp"
})
@XmlRootElement(name = "tableattributes")
public class Tableattributes {

    @XmlAttribute(name = "textheight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String textheight;
    @XmlAttribute(name = "font")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String font;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "columnheadershown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String columnheadershown;
    @XmlAttribute(name = "rowheadershown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rowheadershown;
    @XmlAttribute(name = "headertextheight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String headertextheight;
    @XmlAttribute(name = "headerfont")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String headerfont;
    @XmlAttribute(name = "headerstyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String headerstyle;
    @XmlAttribute(name = "xshown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xshown;
    @XmlAttribute(name = "xresizable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String xresizable;
    @XmlAttribute(name = "xmargin")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmargin;
    @XmlAttribute(name = "yshown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String yshown;
    @XmlAttribute(name = "yresizable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String yresizable;
    @XmlAttribute(name = "ymargin")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ymargin;
    @XmlAttribute(name = "gridcolor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String gridcolor;
    @XmlAttribute(name = "bgcolor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bgcolor;
    @XmlAttribute(name = "textcolor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String textcolor;
    @XmlAttribute(name = "headercolor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String headercolor;
    @XmlAttribute(name = "tabledirection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tabledirection;
    @XmlAttribute(name = "titletextcolor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String titletextcolor;
    @XmlAttribute(name = "titletextheight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String titletextheight;
    @XmlAttribute(name = "titlefont")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String titlefont;
    @XmlAttribute(name = "titlestyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String titlestyle;
    @XmlAttribute(name = "titlejustification")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String titlejustification;
    @XmlAttribute(name = "opaque")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String opaque;
    @XmlAttribute(name = "wraptitletext")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String wraptitletext;
    protected List<Headerrow> headerrow;
    protected Decorationpropertycomp decorationpropertycomp;

    /**
     * Gets the value of the textheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextheight() {
        return textheight;
    }

    /**
     * Sets the value of the textheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextheight(String value) {
        this.textheight = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFont() {
        return font;
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        if (style == null) {
            return "plain";
        } else {
            return style;
        }
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the columnheadershown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnheadershown() {
        if (columnheadershown == null) {
            return "true";
        } else {
            return columnheadershown;
        }
    }

    /**
     * Sets the value of the columnheadershown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnheadershown(String value) {
        this.columnheadershown = value;
    }

    /**
     * Gets the value of the rowheadershown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowheadershown() {
        if (rowheadershown == null) {
            return "false";
        } else {
            return rowheadershown;
        }
    }

    /**
     * Sets the value of the rowheadershown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowheadershown(String value) {
        this.rowheadershown = value;
    }

    /**
     * Gets the value of the headertextheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadertextheight() {
        return headertextheight;
    }

    /**
     * Sets the value of the headertextheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadertextheight(String value) {
        this.headertextheight = value;
    }

    /**
     * Gets the value of the headerfont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderfont() {
        return headerfont;
    }

    /**
     * Sets the value of the headerfont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderfont(String value) {
        this.headerfont = value;
    }

    /**
     * Gets the value of the headerstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeaderstyle() {
        if (headerstyle == null) {
            return "plain";
        } else {
            return headerstyle;
        }
    }

    /**
     * Sets the value of the headerstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeaderstyle(String value) {
        this.headerstyle = value;
    }

    /**
     * Gets the value of the xshown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXshown() {
        if (xshown == null) {
            return "true";
        } else {
            return xshown;
        }
    }

    /**
     * Sets the value of the xshown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXshown(String value) {
        this.xshown = value;
    }

    /**
     * Gets the value of the xresizable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXresizable() {
        if (xresizable == null) {
            return "false";
        } else {
            return xresizable;
        }
    }

    /**
     * Sets the value of the xresizable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXresizable(String value) {
        this.xresizable = value;
    }

    /**
     * Gets the value of the xmargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmargin() {
        return xmargin;
    }

    /**
     * Sets the value of the xmargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmargin(String value) {
        this.xmargin = value;
    }

    /**
     * Gets the value of the yshown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYshown() {
        if (yshown == null) {
            return "true";
        } else {
            return yshown;
        }
    }

    /**
     * Sets the value of the yshown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYshown(String value) {
        this.yshown = value;
    }

    /**
     * Gets the value of the yresizable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYresizable() {
        if (yresizable == null) {
            return "false";
        } else {
            return yresizable;
        }
    }

    /**
     * Sets the value of the yresizable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYresizable(String value) {
        this.yresizable = value;
    }

    /**
     * Gets the value of the ymargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYmargin() {
        return ymargin;
    }

    /**
     * Sets the value of the ymargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYmargin(String value) {
        this.ymargin = value;
    }

    /**
     * Gets the value of the gridcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridcolor() {
        return gridcolor;
    }

    /**
     * Sets the value of the gridcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridcolor(String value) {
        this.gridcolor = value;
    }

    /**
     * Gets the value of the bgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * Sets the value of the bgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgcolor(String value) {
        this.bgcolor = value;
    }

    /**
     * Gets the value of the textcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextcolor() {
        return textcolor;
    }

    /**
     * Sets the value of the textcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextcolor(String value) {
        this.textcolor = value;
    }

    /**
     * Gets the value of the headercolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadercolor() {
        return headercolor;
    }

    /**
     * Sets the value of the headercolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadercolor(String value) {
        this.headercolor = value;
    }

    /**
     * Gets the value of the tabledirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabledirection() {
        if (tabledirection == null) {
            return "true";
        } else {
            return tabledirection;
        }
    }

    /**
     * Sets the value of the tabledirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabledirection(String value) {
        this.tabledirection = value;
    }

    /**
     * Gets the value of the titletextcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitletextcolor() {
        return titletextcolor;
    }

    /**
     * Sets the value of the titletextcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitletextcolor(String value) {
        this.titletextcolor = value;
    }

    /**
     * Gets the value of the titletextheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitletextheight() {
        return titletextheight;
    }

    /**
     * Sets the value of the titletextheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitletextheight(String value) {
        this.titletextheight = value;
    }

    /**
     * Gets the value of the titlefont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlefont() {
        return titlefont;
    }

    /**
     * Sets the value of the titlefont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlefont(String value) {
        this.titlefont = value;
    }

    /**
     * Gets the value of the titlestyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlestyle() {
        if (titlestyle == null) {
            return "plain";
        } else {
            return titlestyle;
        }
    }

    /**
     * Sets the value of the titlestyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlestyle(String value) {
        this.titlestyle = value;
    }

    /**
     * Gets the value of the titlejustification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitlejustification() {
        return titlejustification;
    }

    /**
     * Sets the value of the titlejustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitlejustification(String value) {
        this.titlejustification = value;
    }

    /**
     * Gets the value of the opaque property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpaque() {
        if (opaque == null) {
            return "false";
        } else {
            return opaque;
        }
    }

    /**
     * Sets the value of the opaque property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpaque(String value) {
        this.opaque = value;
    }

    /**
     * Gets the value of the wraptitletext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWraptitletext() {
        if (wraptitletext == null) {
            return "false";
        } else {
            return wraptitletext;
        }
    }

    /**
     * Sets the value of the wraptitletext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWraptitletext(String value) {
        this.wraptitletext = value;
    }

    /**
     * Gets the value of the headerrow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerrow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderrow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Headerrow }
     * 
     * 
     */
    public List<Headerrow> getHeaderrow() {
        if (headerrow == null) {
            headerrow = new ArrayList<Headerrow>();
        }
        return this.headerrow;
    }

    /**
     * Gets the value of the decorationpropertycomp property.
     * 
     * @return
     *     possible object is
     *     {@link Decorationpropertycomp }
     *     
     */
    public Decorationpropertycomp getDecorationpropertycomp() {
        return decorationpropertycomp;
    }

    /**
     * Sets the value of the decorationpropertycomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decorationpropertycomp }
     *     
     */
    public void setDecorationpropertycomp(Decorationpropertycomp value) {
        this.decorationpropertycomp = value;
    }

}
