//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "translationentity")
public class Translationentity {

    @XmlAttribute(name = "entitycode", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entitycode;
    @XmlAttribute(name = "entityvalue", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entityvalue;

    /**
     * Gets the value of the entitycode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitycode() {
        return entitycode;
    }

    /**
     * Sets the value of the entitycode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitycode(String value) {
        this.entitycode = value;
    }

    /**
     * Gets the value of the entityvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityvalue() {
        return entityvalue;
    }

    /**
     * Sets the value of the entityvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityvalue(String value) {
        this.entityvalue = value;
    }

}
