//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "variantref",
    "voptionref",
    "packageinstance"
})
@XmlRootElement(name = "vvehiclemodel")
public class Vvehiclemodel {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "order")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String order;
    @XmlAttribute(name = "parentid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentid;
    @XmlAttribute(name = "baseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baseid;
    @XmlAttribute(name = "takerate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String takerate;
    @XmlAttribute(name = "takeratefleet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String takeratefleet;
    @XmlAttribute(name = "takerateretail")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String takerateretail;
    @XmlAttribute(name = "islockedfleet")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String islockedfleet;
    @XmlAttribute(name = "islockedretail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String islockedretail;
    @XmlAttribute(name = "vvdcount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String vvdcount;
    @XmlAttribute(name = "evdcount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String evdcount;
    protected List<Variantref> variantref;
    protected List<Voptionref> voptionref;
    protected List<Packageinstance> packageinstance;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrder(String value) {
        this.order = value;
    }

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentid(String value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the baseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseid() {
        return baseid;
    }

    /**
     * Sets the value of the baseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseid(String value) {
        this.baseid = value;
    }

    /**
     * Gets the value of the takerate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTakerate() {
        return takerate;
    }

    /**
     * Sets the value of the takerate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTakerate(String value) {
        this.takerate = value;
    }

    /**
     * Gets the value of the takeratefleet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTakeratefleet() {
        return takeratefleet;
    }

    /**
     * Sets the value of the takeratefleet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTakeratefleet(String value) {
        this.takeratefleet = value;
    }

    /**
     * Gets the value of the takerateretail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTakerateretail() {
        return takerateretail;
    }

    /**
     * Sets the value of the takerateretail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTakerateretail(String value) {
        this.takerateretail = value;
    }

    /**
     * Gets the value of the islockedfleet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslockedfleet() {
        if (islockedfleet == null) {
            return "false";
        } else {
            return islockedfleet;
        }
    }

    /**
     * Sets the value of the islockedfleet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslockedfleet(String value) {
        this.islockedfleet = value;
    }

    /**
     * Gets the value of the islockedretail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIslockedretail() {
        if (islockedretail == null) {
            return "false";
        } else {
            return islockedretail;
        }
    }

    /**
     * Sets the value of the islockedretail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIslockedretail(String value) {
        this.islockedretail = value;
    }

    /**
     * Gets the value of the vvdcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVvdcount() {
        return vvdcount;
    }

    /**
     * Sets the value of the vvdcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVvdcount(String value) {
        this.vvdcount = value;
    }

    /**
     * Gets the value of the evdcount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvdcount() {
        return evdcount;
    }

    /**
     * Sets the value of the evdcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvdcount(String value) {
        this.evdcount = value;
    }

    /**
     * Gets the value of the variantref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variantref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariantref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Variantref }
     * 
     * 
     */
    public List<Variantref> getVariantref() {
        if (variantref == null) {
            variantref = new ArrayList<Variantref>();
        }
        return this.variantref;
    }

    /**
     * Gets the value of the voptionref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voptionref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoptionref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Voptionref }
     * 
     * 
     */
    public List<Voptionref> getVoptionref() {
        if (voptionref == null) {
            voptionref = new ArrayList<Voptionref>();
        }
        return this.voptionref;
    }

    /**
     * Gets the value of the packageinstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageinstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageinstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Packageinstance }
     * 
     * 
     */
    public List<Packageinstance> getPackageinstance() {
        if (packageinstance == null) {
            packageinstance = new ArrayList<Packageinstance>();
        }
        return this.packageinstance;
    }

}
