//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namedquery"
})
@XmlRootElement(name = "workbooktemplate")
public class Workbooktemplate {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "description")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String description;
    @XmlAttribute(name = "modified")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modified;
    @XmlAttribute(name = "folderpath")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String folderpath;
    @XmlAttribute(name = "pluginref", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pluginref;
    @XmlAttribute(name = "pluginver", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pluginver;
    @XmlAttribute(name = "params")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String params;
    protected Namedquery namedquery;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModified() {
        if (modified == null) {
            return "0";
        } else {
            return modified;
        }
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModified(String value) {
        this.modified = value;
    }

    /**
     * Gets the value of the folderpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFolderpath() {
        return folderpath;
    }

    /**
     * Sets the value of the folderpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFolderpath(String value) {
        this.folderpath = value;
    }

    /**
     * Gets the value of the pluginref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPluginref() {
        return pluginref;
    }

    /**
     * Sets the value of the pluginref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPluginref(String value) {
        this.pluginref = value;
    }

    /**
     * Gets the value of the pluginver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPluginver() {
        return pluginver;
    }

    /**
     * Sets the value of the pluginver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPluginver(String value) {
        this.pluginver = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParams(String value) {
        this.params = value;
    }

    /**
     * Gets the value of the namedquery property.
     * 
     * @return
     *     possible object is
     *     {@link Namedquery }
     *     
     */
    public Namedquery getNamedquery() {
        return namedquery;
    }

    /**
     * Sets the value of the namedquery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Namedquery }
     *     
     */
    public void setNamedquery(Namedquery value) {
        this.namedquery = value;
    }

}
