//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "xreftext")
public class Xreftext {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "baseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baseid;
    @XmlAttribute(name = "x", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String x;
    @XmlAttribute(name = "y", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String y;
    @XmlAttribute(name = "height", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String height;
    @XmlAttribute(name = "rotation")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rotation;
    @XmlAttribute(name = "boxing")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String boxing;
    @XmlAttribute(name = "wrap")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String wrap;
    @XmlAttribute(name = "recentreonflip")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String recentreonflip;
    @XmlAttribute(name = "recenter")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String recenter;
    @XmlAttribute(name = "hjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hjust;
    @XmlAttribute(name = "vjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vjust;
    @XmlAttribute(name = "visibility")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visibility;
    @XmlAttribute(name = "font")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String font;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String style;
    @XmlAttribute(name = "autoflip")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String autoflip;
    @XmlAttribute(name = "decorationid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decorationid;
    @XmlAttribute(name = "decorationname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decorationname;
    @XmlAttribute(name = "ispositionlocked")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ispositionlocked;
    @XmlAttribute(name = "parentid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentid;
    @XmlAttribute(name = "layernum")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String layernum;
    @XmlAttribute(name = "attributeref")
    @XmlIDREF
    protected Object attributeref;
    @XmlAttribute(name = "lockeddecorationref")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lockeddecorationref;
    @XmlAttribute(name = "isexcludefromapplystyle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isexcludefromapplystyle;
    @XmlAttribute(name = "boundswidth")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String boundswidth;
    @XmlAttribute(name = "boundsheight")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String boundsheight;
    @XmlAttribute(name = "roundingtype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String roundingtype;
    @XmlAttribute(name = "decimalplaces")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decimalplaces;
    @XmlAttribute(name = "customroundingvalue")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customroundingvalue;
    @XmlAttribute(name = "decimaldelimiter")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decimaldelimiter;
    @XmlAttribute(name = "freerotateangle")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String freerotateangle;
    @XmlAttribute(name = "ballooningshape")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ballooningshape;
    @XmlAttribute(name = "balloonlinethickness")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String balloonlinethickness;
    @XmlAttribute(name = "blockindex")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String blockindex;
    @XmlAttribute(name = "blocktext")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String blocktext;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the baseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseid() {
        return baseid;
    }

    /**
     * Sets the value of the baseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseid(String value) {
        this.baseid = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setX(String value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setY(String value) {
        this.y = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRotation() {
        if (rotation == null) {
            return "0";
        } else {
            return rotation;
        }
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRotation(String value) {
        this.rotation = value;
    }

    /**
     * Gets the value of the boxing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoxing() {
        return boxing;
    }

    /**
     * Sets the value of the boxing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoxing(String value) {
        this.boxing = value;
    }

    /**
     * Gets the value of the wrap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrap() {
        return wrap;
    }

    /**
     * Sets the value of the wrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrap(String value) {
        this.wrap = value;
    }

    /**
     * Gets the value of the recentreonflip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecentreonflip() {
        return recentreonflip;
    }

    /**
     * Sets the value of the recentreonflip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecentreonflip(String value) {
        this.recentreonflip = value;
    }

    /**
     * Gets the value of the recenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecenter() {
        return recenter;
    }

    /**
     * Sets the value of the recenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecenter(String value) {
        this.recenter = value;
    }

    /**
     * Gets the value of the hjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHjust() {
        if (hjust == null) {
            return "left";
        } else {
            return hjust;
        }
    }

    /**
     * Sets the value of the hjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHjust(String value) {
        this.hjust = value;
    }

    /**
     * Gets the value of the vjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjust() {
        if (vjust == null) {
            return "bottom";
        } else {
            return vjust;
        }
    }

    /**
     * Sets the value of the vjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjust(String value) {
        this.vjust = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        if (visibility == null) {
            return "true";
        } else {
            return visibility;
        }
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the font property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFont() {
        if (font == null) {
            return "Stroke";
        } else {
            return font;
        }
    }

    /**
     * Sets the value of the font property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFont(String value) {
        this.font = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        if (style == null) {
            return "plain";
        } else {
            return style;
        }
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the autoflip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoflip() {
        if (autoflip == null) {
            return "true";
        } else {
            return autoflip;
        }
    }

    /**
     * Sets the value of the autoflip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoflip(String value) {
        this.autoflip = value;
    }

    /**
     * Gets the value of the decorationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecorationid() {
        return decorationid;
    }

    /**
     * Sets the value of the decorationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecorationid(String value) {
        this.decorationid = value;
    }

    /**
     * Gets the value of the decorationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecorationname() {
        return decorationname;
    }

    /**
     * Sets the value of the decorationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecorationname(String value) {
        this.decorationname = value;
    }

    /**
     * Gets the value of the ispositionlocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIspositionlocked() {
        if (ispositionlocked == null) {
            return "false";
        } else {
            return ispositionlocked;
        }
    }

    /**
     * Sets the value of the ispositionlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIspositionlocked(String value) {
        this.ispositionlocked = value;
    }

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentid(String value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the layernum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayernum() {
        return layernum;
    }

    /**
     * Sets the value of the layernum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayernum(String value) {
        this.layernum = value;
    }

    /**
     * Gets the value of the attributeref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAttributeref() {
        return attributeref;
    }

    /**
     * Sets the value of the attributeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAttributeref(Object value) {
        this.attributeref = value;
    }

    /**
     * Gets the value of the lockeddecorationref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockeddecorationref() {
        return lockeddecorationref;
    }

    /**
     * Sets the value of the lockeddecorationref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockeddecorationref(String value) {
        this.lockeddecorationref = value;
    }

    /**
     * Gets the value of the isexcludefromapplystyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsexcludefromapplystyle() {
        if (isexcludefromapplystyle == null) {
            return "false";
        } else {
            return isexcludefromapplystyle;
        }
    }

    /**
     * Sets the value of the isexcludefromapplystyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsexcludefromapplystyle(String value) {
        this.isexcludefromapplystyle = value;
    }

    /**
     * Gets the value of the boundswidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundswidth() {
        return boundswidth;
    }

    /**
     * Sets the value of the boundswidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundswidth(String value) {
        this.boundswidth = value;
    }

    /**
     * Gets the value of the boundsheight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundsheight() {
        return boundsheight;
    }

    /**
     * Sets the value of the boundsheight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundsheight(String value) {
        this.boundsheight = value;
    }

    /**
     * Gets the value of the roundingtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundingtype() {
        return roundingtype;
    }

    /**
     * Sets the value of the roundingtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundingtype(String value) {
        this.roundingtype = value;
    }

    /**
     * Gets the value of the decimalplaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalplaces() {
        return decimalplaces;
    }

    /**
     * Sets the value of the decimalplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalplaces(String value) {
        this.decimalplaces = value;
    }

    /**
     * Gets the value of the customroundingvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomroundingvalue() {
        return customroundingvalue;
    }

    /**
     * Sets the value of the customroundingvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomroundingvalue(String value) {
        this.customroundingvalue = value;
    }

    /**
     * Gets the value of the decimaldelimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimaldelimiter() {
        return decimaldelimiter;
    }

    /**
     * Sets the value of the decimaldelimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimaldelimiter(String value) {
        this.decimaldelimiter = value;
    }

    /**
     * Gets the value of the freerotateangle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreerotateangle() {
        return freerotateangle;
    }

    /**
     * Sets the value of the freerotateangle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreerotateangle(String value) {
        this.freerotateangle = value;
    }

    /**
     * Gets the value of the ballooningshape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBallooningshape() {
        if (ballooningshape == null) {
            return "NONE";
        } else {
            return ballooningshape;
        }
    }

    /**
     * Sets the value of the ballooningshape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBallooningshape(String value) {
        this.ballooningshape = value;
    }

    /**
     * Gets the value of the balloonlinethickness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalloonlinethickness() {
        return balloonlinethickness;
    }

    /**
     * Sets the value of the balloonlinethickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalloonlinethickness(String value) {
        this.balloonlinethickness = value;
    }

    /**
     * Gets the value of the blockindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockindex() {
        if (blockindex == null) {
            return "0";
        } else {
            return blockindex;
        }
    }

    /**
     * Sets the value of the blockindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockindex(String value) {
        this.blockindex = value;
    }

    /**
     * Gets the value of the blocktext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlocktext() {
        return blocktext;
    }

    /**
     * Sets the value of the blocktext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlocktext(String value) {
        this.blocktext = value;
    }

}
