//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rule",
    "refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D"
})
@XmlRootElement(name = "bundle")
public class Bundle {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "shortdescription")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shortdescription;
    @XmlAttribute(name = "nameindex")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nameindex;
    @XmlAttribute(name = "startnoderef")
    @XmlIDREF
    protected Object startnoderef;
    @XmlAttribute(name = "endnoderef")
    @XmlIDREF
    protected Object endnoderef;
    @XmlAttribute(name = "startnode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String startnode;
    @XmlAttribute(name = "endnode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String endnode;
    @XmlAttribute(name = "startroute")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String startroute;
    @XmlAttribute(name = "endroute")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String endroute;
    @XmlAttribute(name = "length", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String length;
    @XmlAttribute(name = "lengthuserdefined")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lengthuserdefined;
    @XmlAttribute(name = "brlength")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String brlength;
    @XmlAttribute(name = "grlength")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String grlength;
    @XmlAttribute(name = "grang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String grang;
    @XmlAttribute(name = "maxallowedwidth")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String maxallowedwidth;
    @XmlAttribute(name = "minbendradius")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String minbendradius;
    @XmlAttribute(name = "mcadid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mcadid;
    @XmlAttribute(name = "optionexpression")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionexpression;
    @XmlAttribute(name = "circuit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String circuit;
    @XmlAttribute(name = "parentid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentid;
    @XmlAttribute(name = "baseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baseid;
    @XmlAttribute(name = "variantindex")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String variantindex;
    @XmlAttribute(name = "optionexpressiontype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String optionexpressiontype;
    @XmlAttribute(name = "node1ref")
    @XmlIDREF
    protected Object node1Ref;
    @XmlAttribute(name = "node2ref")
    @XmlIDREF
    protected Object node2Ref;
    @XmlAttribute(name = "width")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String width;
    @XmlAttribute(name = "widthwithinsulations")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String widthwithinsulations;
    @XmlAttribute(name = "numwires")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numwires;
    @XmlAttribute(name = "nummults")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nummults;
    @XmlAttribute(name = "numtapes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numtapes;
    @XmlAttribute(name = "numtubes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String numtubes;
    @XmlAttribute(name = "node1numwires")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node1Numwires;
    @XmlAttribute(name = "node1nummults")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node1Nummults;
    @XmlAttribute(name = "node1numtapes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node1Numtapes;
    @XmlAttribute(name = "node1numtubes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node1Numtubes;
    @XmlAttribute(name = "widthnode1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String widthnode1;
    @XmlAttribute(name = "widthwithinsulationnode1")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String widthwithinsulationnode1;
    @XmlAttribute(name = "node2numwires")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node2Numwires;
    @XmlAttribute(name = "node2nummults")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node2Nummults;
    @XmlAttribute(name = "node2numtapes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node2Numtapes;
    @XmlAttribute(name = "node2numtubes")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String node2Numtubes;
    @XmlAttribute(name = "widthnode2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String widthnode2;
    @XmlAttribute(name = "widthwithinsulationnode2")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String widthwithinsulationnode2;
    @XmlAttribute(name = "overriddenSegmentOrigin")
    @XmlIDREF
    protected Object overriddenSegmentOrigin;
    protected Rule rule;
    @XmlElements({
        @XmlElement(name = "refednode", type = Refednode.class),
        @XmlElement(name = "bundleregion", type = Bundleregion.class),
        @XmlElement(name = "property", type = Property.class),
        @XmlElement(name = "objtag", type = Objtag.class),
        @XmlElement(name = "location3d", type = Location3D.class)
    })
    protected List<Object> refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the shortdescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortdescription() {
        return shortdescription;
    }

    /**
     * Sets the value of the shortdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortdescription(String value) {
        this.shortdescription = value;
    }

    /**
     * Gets the value of the nameindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameindex() {
        if (nameindex == null) {
            return "-1";
        } else {
            return nameindex;
        }
    }

    /**
     * Sets the value of the nameindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameindex(String value) {
        this.nameindex = value;
    }

    /**
     * Gets the value of the startnoderef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getStartnoderef() {
        return startnoderef;
    }

    /**
     * Sets the value of the startnoderef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setStartnoderef(Object value) {
        this.startnoderef = value;
    }

    /**
     * Gets the value of the endnoderef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEndnoderef() {
        return endnoderef;
    }

    /**
     * Sets the value of the endnoderef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEndnoderef(Object value) {
        this.endnoderef = value;
    }

    /**
     * Gets the value of the startnode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartnode() {
        return startnode;
    }

    /**
     * Sets the value of the startnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartnode(String value) {
        this.startnode = value;
    }

    /**
     * Gets the value of the endnode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndnode() {
        return endnode;
    }

    /**
     * Sets the value of the endnode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndnode(String value) {
        this.endnode = value;
    }

    /**
     * Gets the value of the startroute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartroute() {
        return startroute;
    }

    /**
     * Sets the value of the startroute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartroute(String value) {
        this.startroute = value;
    }

    /**
     * Gets the value of the endroute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndroute() {
        return endroute;
    }

    /**
     * Sets the value of the endroute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndroute(String value) {
        this.endroute = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the lengthuserdefined property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthuserdefined() {
        if (lengthuserdefined == null) {
            return "false";
        } else {
            return lengthuserdefined;
        }
    }

    /**
     * Sets the value of the lengthuserdefined property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthuserdefined(String value) {
        this.lengthuserdefined = value;
    }

    /**
     * Gets the value of the brlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrlength() {
        return brlength;
    }

    /**
     * Sets the value of the brlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrlength(String value) {
        this.brlength = value;
    }

    /**
     * Gets the value of the grlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrlength() {
        return grlength;
    }

    /**
     * Sets the value of the grlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrlength(String value) {
        this.grlength = value;
    }

    /**
     * Gets the value of the grang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrang() {
        return grang;
    }

    /**
     * Sets the value of the grang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrang(String value) {
        this.grang = value;
    }

    /**
     * Gets the value of the maxallowedwidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxallowedwidth() {
        return maxallowedwidth;
    }

    /**
     * Sets the value of the maxallowedwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxallowedwidth(String value) {
        this.maxallowedwidth = value;
    }

    /**
     * Gets the value of the minbendradius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinbendradius() {
        return minbendradius;
    }

    /**
     * Sets the value of the minbendradius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinbendradius(String value) {
        this.minbendradius = value;
    }

    /**
     * Gets the value of the mcadid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcadid() {
        return mcadid;
    }

    /**
     * Sets the value of the mcadid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcadid(String value) {
        this.mcadid = value;
    }

    /**
     * Gets the value of the optionexpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpression() {
        return optionexpression;
    }

    /**
     * Sets the value of the optionexpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpression(String value) {
        this.optionexpression = value;
    }

    /**
     * Gets the value of the circuit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuit() {
        return circuit;
    }

    /**
     * Sets the value of the circuit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuit(String value) {
        this.circuit = value;
    }

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentid(String value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the baseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseid() {
        return baseid;
    }

    /**
     * Sets the value of the baseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseid(String value) {
        this.baseid = value;
    }

    /**
     * Gets the value of the variantindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantindex() {
        return variantindex;
    }

    /**
     * Sets the value of the variantindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantindex(String value) {
        this.variantindex = value;
    }

    /**
     * Gets the value of the optionexpressiontype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionexpressiontype() {
        return optionexpressiontype;
    }

    /**
     * Sets the value of the optionexpressiontype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionexpressiontype(String value) {
        this.optionexpressiontype = value;
    }

    /**
     * Gets the value of the node1Ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNode1Ref() {
        return node1Ref;
    }

    /**
     * Sets the value of the node1Ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNode1Ref(Object value) {
        this.node1Ref = value;
    }

    /**
     * Gets the value of the node2Ref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNode2Ref() {
        return node2Ref;
    }

    /**
     * Sets the value of the node2Ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNode2Ref(Object value) {
        this.node2Ref = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the widthwithinsulations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthwithinsulations() {
        return widthwithinsulations;
    }

    /**
     * Sets the value of the widthwithinsulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthwithinsulations(String value) {
        this.widthwithinsulations = value;
    }

    /**
     * Gets the value of the numwires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumwires() {
        return numwires;
    }

    /**
     * Sets the value of the numwires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumwires(String value) {
        this.numwires = value;
    }

    /**
     * Gets the value of the nummults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNummults() {
        return nummults;
    }

    /**
     * Sets the value of the nummults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNummults(String value) {
        this.nummults = value;
    }

    /**
     * Gets the value of the numtapes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumtapes() {
        return numtapes;
    }

    /**
     * Sets the value of the numtapes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumtapes(String value) {
        this.numtapes = value;
    }

    /**
     * Gets the value of the numtubes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumtubes() {
        return numtubes;
    }

    /**
     * Sets the value of the numtubes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumtubes(String value) {
        this.numtubes = value;
    }

    /**
     * Gets the value of the node1Numwires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode1Numwires() {
        return node1Numwires;
    }

    /**
     * Sets the value of the node1Numwires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode1Numwires(String value) {
        this.node1Numwires = value;
    }

    /**
     * Gets the value of the node1Nummults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode1Nummults() {
        return node1Nummults;
    }

    /**
     * Sets the value of the node1Nummults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode1Nummults(String value) {
        this.node1Nummults = value;
    }

    /**
     * Gets the value of the node1Numtapes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode1Numtapes() {
        return node1Numtapes;
    }

    /**
     * Sets the value of the node1Numtapes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode1Numtapes(String value) {
        this.node1Numtapes = value;
    }

    /**
     * Gets the value of the node1Numtubes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode1Numtubes() {
        return node1Numtubes;
    }

    /**
     * Sets the value of the node1Numtubes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode1Numtubes(String value) {
        this.node1Numtubes = value;
    }

    /**
     * Gets the value of the widthnode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthnode1() {
        return widthnode1;
    }

    /**
     * Sets the value of the widthnode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthnode1(String value) {
        this.widthnode1 = value;
    }

    /**
     * Gets the value of the widthwithinsulationnode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthwithinsulationnode1() {
        return widthwithinsulationnode1;
    }

    /**
     * Sets the value of the widthwithinsulationnode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthwithinsulationnode1(String value) {
        this.widthwithinsulationnode1 = value;
    }

    /**
     * Gets the value of the node2Numwires property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode2Numwires() {
        return node2Numwires;
    }

    /**
     * Sets the value of the node2Numwires property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode2Numwires(String value) {
        this.node2Numwires = value;
    }

    /**
     * Gets the value of the node2Nummults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode2Nummults() {
        return node2Nummults;
    }

    /**
     * Sets the value of the node2Nummults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode2Nummults(String value) {
        this.node2Nummults = value;
    }

    /**
     * Gets the value of the node2Numtapes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode2Numtapes() {
        return node2Numtapes;
    }

    /**
     * Sets the value of the node2Numtapes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode2Numtapes(String value) {
        this.node2Numtapes = value;
    }

    /**
     * Gets the value of the node2Numtubes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode2Numtubes() {
        return node2Numtubes;
    }

    /**
     * Sets the value of the node2Numtubes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode2Numtubes(String value) {
        this.node2Numtubes = value;
    }

    /**
     * Gets the value of the widthnode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthnode2() {
        return widthnode2;
    }

    /**
     * Sets the value of the widthnode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthnode2(String value) {
        this.widthnode2 = value;
    }

    /**
     * Gets the value of the widthwithinsulationnode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidthwithinsulationnode2() {
        return widthwithinsulationnode2;
    }

    /**
     * Sets the value of the widthwithinsulationnode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidthwithinsulationnode2(String value) {
        this.widthwithinsulationnode2 = value;
    }

    /**
     * Gets the value of the overriddenSegmentOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getOverriddenSegmentOrigin() {
        return overriddenSegmentOrigin;
    }

    /**
     * Sets the value of the overriddenSegmentOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setOverriddenSegmentOrigin(Object value) {
        this.overriddenSegmentOrigin = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link Rule }
     *     
     */
    public Rule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rule }
     *     
     */
    public void setRule(Rule value) {
        this.rule = value;
    }

    /**
     * Gets the value of the refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefednodeOrBundleregionOrPropertyOrObjtagOrLocation3D().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Refednode }
     * {@link Bundleregion }
     * {@link Property }
     * {@link Objtag }
     * {@link Location3D }
     * 
     * 
     */
    public List<Object> getRefednodeOrBundleregionOrPropertyOrObjtagOrLocation3D() {
        if (refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D == null) {
            refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D = new ArrayList<Object>();
        }
        return this.refednodeOrBundleregionOrPropertyOrObjtagOrLocation3D;
    }

}
