//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namedquery",
    "namedexpressionOrDefinedexpression"
})
@XmlRootElement(name = "costformulaelement")
public class Costformulaelement {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "index", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String index;
    @XmlElement(required = true)
    protected Namedquery namedquery;
    @XmlElements({
        @XmlElement(name = "namedexpression", required = true, type = Namedexpression.class),
        @XmlElement(name = "definedexpression", required = true, type = Definedexpression.class)
    })
    protected List<Object> namedexpressionOrDefinedexpression;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the namedquery property.
     * 
     * @return
     *     possible object is
     *     {@link Namedquery }
     *     
     */
    public Namedquery getNamedquery() {
        return namedquery;
    }

    /**
     * Sets the value of the namedquery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Namedquery }
     *     
     */
    public void setNamedquery(Namedquery value) {
        this.namedquery = value;
    }

    /**
     * Gets the value of the namedexpressionOrDefinedexpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namedexpressionOrDefinedexpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamedexpressionOrDefinedexpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Namedexpression }
     * {@link Definedexpression }
     * 
     * 
     */
    public List<Object> getNamedexpressionOrDefinedexpression() {
        if (namedexpressionOrDefinedexpression == null) {
            namedexpressionOrDefinedexpression = new ArrayList<Object>();
        }
        return this.namedexpressionOrDefinedexpression;
    }

}
