//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "harnbundleentityconfiguration")
public class Harnbundleentityconfiguration {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "modified")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modified;
    @XmlAttribute(name = "parentid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentid;
    @XmlAttribute(name = "baseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baseid;
    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "subtype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subtype;
    @XmlAttribute(name = "entitycfgtypevalue", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String entitycfgtypevalue;
    @XmlAttribute(name = "decorationstyleref")
    @XmlIDREF
    protected Object decorationstyleref;
    @XmlAttribute(name = "graphicsstyleref")
    @XmlIDREF
    protected Object graphicsstyleref;
    @XmlAttribute(name = "internodeoptionstyleref")
    @XmlIDREF
    protected Object internodeoptionstyleref;
    @XmlAttribute(name = "conditionalshapestyleref")
    @XmlIDREF
    protected Object conditionalshapestyleref;
    @XmlAttribute(name = "ancestor")
    @XmlIDREF
    protected Object ancestor;
    @XmlAttribute(name = "isshapevisible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isshapevisible;
    @XmlAttribute(name = "isshapevisibilityoverridable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isshapevisibilityoverridable;
    @XmlAttribute(name = "isdecorationvisible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isdecorationvisible;
    @XmlAttribute(name = "isdecorationvisibilityoverridable")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isdecorationvisibilityoverridable;
    @XmlAttribute(name = "bundlewidthgraphicsstyleref")
    @XmlIDREF
    protected Object bundlewidthgraphicsstyleref;
    @XmlAttribute(name = "bundlewidthinsgraphicsstyleref")
    @XmlIDREF
    protected Object bundlewidthinsgraphicsstyleref;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModified(String value) {
        this.modified = value;
    }

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentid(String value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the baseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseid() {
        return baseid;
    }

    /**
     * Sets the value of the baseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseid(String value) {
        this.baseid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the subtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * Sets the value of the subtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubtype(String value) {
        this.subtype = value;
    }

    /**
     * Gets the value of the entitycfgtypevalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitycfgtypevalue() {
        return entitycfgtypevalue;
    }

    /**
     * Sets the value of the entitycfgtypevalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitycfgtypevalue(String value) {
        this.entitycfgtypevalue = value;
    }

    /**
     * Gets the value of the decorationstyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDecorationstyleref() {
        return decorationstyleref;
    }

    /**
     * Sets the value of the decorationstyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDecorationstyleref(Object value) {
        this.decorationstyleref = value;
    }

    /**
     * Gets the value of the graphicsstyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGraphicsstyleref() {
        return graphicsstyleref;
    }

    /**
     * Sets the value of the graphicsstyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGraphicsstyleref(Object value) {
        this.graphicsstyleref = value;
    }

    /**
     * Gets the value of the internodeoptionstyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getInternodeoptionstyleref() {
        return internodeoptionstyleref;
    }

    /**
     * Sets the value of the internodeoptionstyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setInternodeoptionstyleref(Object value) {
        this.internodeoptionstyleref = value;
    }

    /**
     * Gets the value of the conditionalshapestyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getConditionalshapestyleref() {
        return conditionalshapestyleref;
    }

    /**
     * Sets the value of the conditionalshapestyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setConditionalshapestyleref(Object value) {
        this.conditionalshapestyleref = value;
    }

    /**
     * Gets the value of the ancestor property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAncestor() {
        return ancestor;
    }

    /**
     * Sets the value of the ancestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAncestor(Object value) {
        this.ancestor = value;
    }

    /**
     * Gets the value of the isshapevisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsshapevisible() {
        if (isshapevisible == null) {
            return "true";
        } else {
            return isshapevisible;
        }
    }

    /**
     * Sets the value of the isshapevisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsshapevisible(String value) {
        this.isshapevisible = value;
    }

    /**
     * Gets the value of the isshapevisibilityoverridable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsshapevisibilityoverridable() {
        if (isshapevisibilityoverridable == null) {
            return "true";
        } else {
            return isshapevisibilityoverridable;
        }
    }

    /**
     * Sets the value of the isshapevisibilityoverridable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsshapevisibilityoverridable(String value) {
        this.isshapevisibilityoverridable = value;
    }

    /**
     * Gets the value of the isdecorationvisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsdecorationvisible() {
        if (isdecorationvisible == null) {
            return "true";
        } else {
            return isdecorationvisible;
        }
    }

    /**
     * Sets the value of the isdecorationvisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsdecorationvisible(String value) {
        this.isdecorationvisible = value;
    }

    /**
     * Gets the value of the isdecorationvisibilityoverridable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsdecorationvisibilityoverridable() {
        if (isdecorationvisibilityoverridable == null) {
            return "true";
        } else {
            return isdecorationvisibilityoverridable;
        }
    }

    /**
     * Sets the value of the isdecorationvisibilityoverridable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsdecorationvisibilityoverridable(String value) {
        this.isdecorationvisibilityoverridable = value;
    }

    /**
     * Gets the value of the bundlewidthgraphicsstyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBundlewidthgraphicsstyleref() {
        return bundlewidthgraphicsstyleref;
    }

    /**
     * Sets the value of the bundlewidthgraphicsstyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBundlewidthgraphicsstyleref(Object value) {
        this.bundlewidthgraphicsstyleref = value;
    }

    /**
     * Gets the value of the bundlewidthinsgraphicsstyleref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBundlewidthinsgraphicsstyleref() {
        return bundlewidthinsgraphicsstyleref;
    }

    /**
     * Sets the value of the bundlewidthinsgraphicsstyleref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBundlewidthinsgraphicsstyleref(Object value) {
        this.bundlewidthinsgraphicsstyleref = value;
    }

}
