//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rule",
    "connectivity",
    "cavityOrPropertyOrObjtag",
    "bshellconnection",
    "bundlefanout",
    "harnessnoderef",
    "topoinline"
})
@XmlRootElement(name = "inlineconnector")
public class Inlineconnector {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "nameindex")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nameindex;
    @XmlAttribute(name = "physicaltargetref")
    @XmlIDREF
    protected Object physicaltargetref;
    @XmlAttribute(name = "parentid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String parentid;
    @XmlAttribute(name = "baseid")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String baseid;
    @XmlAttribute(name = "modified")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String modified;
    @XmlAttribute(name = "mate")
    @XmlIDREF
    protected Object mate;
    @XmlAttribute(name = "mapperref")
    @XmlIDREF
    protected Object mapperref;
    @XmlAttribute(name = "partdesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partdesc;
    @XmlAttribute(name = "colorcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String colorcode;
    @XmlAttribute(name = "colordesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String colordesc;
    @XmlAttribute(name = "unitofmeasure")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unitofmeasure;
    @XmlAttribute(name = "materialcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String materialcode;
    @XmlAttribute(name = "matcodedesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String matcodedesc;
    @XmlAttribute(name = "typecode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String typecode;
    @XmlAttribute(name = "typecodedesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String typecodedesc;
    @XmlAttribute(name = "groupname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String groupname;
    protected Rule rule;
    @XmlElement(required = true)
    protected Connectivity connectivity;
    @XmlElements({
        @XmlElement(name = "cavity", type = Cavity.class),
        @XmlElement(name = "property", type = Property.class),
        @XmlElement(name = "objtag", type = Objtag.class)
    })
    protected List<Object> cavityOrPropertyOrObjtag;
    protected List<Bshellconnection> bshellconnection;
    protected Bundlefanout bundlefanout;
    @XmlElement(required = true)
    protected List<Harnessnoderef> harnessnoderef;
    @XmlElement(required = true)
    protected Topoinline topoinline;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nameindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameindex() {
        if (nameindex == null) {
            return "-1";
        } else {
            return nameindex;
        }
    }

    /**
     * Sets the value of the nameindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameindex(String value) {
        this.nameindex = value;
    }

    /**
     * Gets the value of the physicaltargetref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPhysicaltargetref() {
        return physicaltargetref;
    }

    /**
     * Sets the value of the physicaltargetref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPhysicaltargetref(Object value) {
        this.physicaltargetref = value;
    }

    /**
     * Gets the value of the parentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * Sets the value of the parentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentid(String value) {
        this.parentid = value;
    }

    /**
     * Gets the value of the baseid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseid() {
        return baseid;
    }

    /**
     * Sets the value of the baseid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseid(String value) {
        this.baseid = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModified() {
        if (modified == null) {
            return "0";
        } else {
            return modified;
        }
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModified(String value) {
        this.modified = value;
    }

    /**
     * Gets the value of the mate property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMate() {
        return mate;
    }

    /**
     * Sets the value of the mate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMate(Object value) {
        this.mate = value;
    }

    /**
     * Gets the value of the mapperref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMapperref() {
        return mapperref;
    }

    /**
     * Sets the value of the mapperref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMapperref(Object value) {
        this.mapperref = value;
    }

    /**
     * Gets the value of the partdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartdesc() {
        return partdesc;
    }

    /**
     * Sets the value of the partdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartdesc(String value) {
        this.partdesc = value;
    }

    /**
     * Gets the value of the colorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorcode() {
        return colorcode;
    }

    /**
     * Sets the value of the colorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorcode(String value) {
        this.colorcode = value;
    }

    /**
     * Gets the value of the colordesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColordesc() {
        return colordesc;
    }

    /**
     * Sets the value of the colordesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColordesc(String value) {
        this.colordesc = value;
    }

    /**
     * Gets the value of the unitofmeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitofmeasure() {
        return unitofmeasure;
    }

    /**
     * Sets the value of the unitofmeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitofmeasure(String value) {
        this.unitofmeasure = value;
    }

    /**
     * Gets the value of the materialcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialcode() {
        return materialcode;
    }

    /**
     * Sets the value of the materialcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialcode(String value) {
        this.materialcode = value;
    }

    /**
     * Gets the value of the matcodedesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatcodedesc() {
        return matcodedesc;
    }

    /**
     * Sets the value of the matcodedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatcodedesc(String value) {
        this.matcodedesc = value;
    }

    /**
     * Gets the value of the typecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * Sets the value of the typecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypecode(String value) {
        this.typecode = value;
    }

    /**
     * Gets the value of the typecodedesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypecodedesc() {
        return typecodedesc;
    }

    /**
     * Sets the value of the typecodedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypecodedesc(String value) {
        this.typecodedesc = value;
    }

    /**
     * Gets the value of the groupname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * Sets the value of the groupname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupname(String value) {
        this.groupname = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link Rule }
     *     
     */
    public Rule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rule }
     *     
     */
    public void setRule(Rule value) {
        this.rule = value;
    }

    /**
     * Gets the value of the connectivity property.
     * 
     * @return
     *     possible object is
     *     {@link Connectivity }
     *     
     */
    public Connectivity getConnectivity() {
        return connectivity;
    }

    /**
     * Sets the value of the connectivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Connectivity }
     *     
     */
    public void setConnectivity(Connectivity value) {
        this.connectivity = value;
    }

    /**
     * Gets the value of the cavityOrPropertyOrObjtag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cavityOrPropertyOrObjtag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCavityOrPropertyOrObjtag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cavity }
     * {@link Property }
     * {@link Objtag }
     * 
     * 
     */
    public List<Object> getCavityOrPropertyOrObjtag() {
        if (cavityOrPropertyOrObjtag == null) {
            cavityOrPropertyOrObjtag = new ArrayList<Object>();
        }
        return this.cavityOrPropertyOrObjtag;
    }

    /**
     * Gets the value of the bshellconnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bshellconnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBshellconnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bshellconnection }
     * 
     * 
     */
    public List<Bshellconnection> getBshellconnection() {
        if (bshellconnection == null) {
            bshellconnection = new ArrayList<Bshellconnection>();
        }
        return this.bshellconnection;
    }

    /**
     * Gets the value of the bundlefanout property.
     * 
     * @return
     *     possible object is
     *     {@link Bundlefanout }
     *     
     */
    public Bundlefanout getBundlefanout() {
        return bundlefanout;
    }

    /**
     * Sets the value of the bundlefanout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bundlefanout }
     *     
     */
    public void setBundlefanout(Bundlefanout value) {
        this.bundlefanout = value;
    }

    /**
     * Gets the value of the harnessnoderef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the harnessnoderef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHarnessnoderef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Harnessnoderef }
     * 
     * 
     */
    public List<Harnessnoderef> getHarnessnoderef() {
        if (harnessnoderef == null) {
            harnessnoderef = new ArrayList<Harnessnoderef>();
        }
        return this.harnessnoderef;
    }

    /**
     * Gets the value of the topoinline property.
     * 
     * @return
     *     possible object is
     *     {@link Topoinline }
     *     
     */
    public Topoinline getTopoinline() {
        return topoinline;
    }

    /**
     * Sets the value of the topoinline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topoinline }
     *     
     */
    public void setTopoinline(Topoinline value) {
        this.topoinline = value;
    }

}
