//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "insulationlayerdetails")
public class Insulationlayerdetails {

    @XmlAttribute(name = "lengthu", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lengthu;
    @XmlAttribute(name = "libraryref")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String libraryref;
    @XmlAttribute(name = "partnumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partnumber;
    @XmlAttribute(name = "partrevision")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partrevision;
    @XmlAttribute(name = "customerpartnumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customerpartnumber;
    @XmlAttribute(name = "customername")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String customername;
    @XmlAttribute(name = "supplierpartnumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String supplierpartnumber;
    @XmlAttribute(name = "suppliername")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String suppliername;
    @XmlAttribute(name = "layer")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String layer;
    @XmlAttribute(name = "instype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String instype;
    @XmlAttribute(name = "typecode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String typecode;
    @XmlAttribute(name = "colorcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String colorcode;
    @XmlAttribute(name = "materialcode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String materialcode;
    @XmlAttribute(name = "cutback")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cutback;
    @XmlAttribute(name = "overlaps")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String overlaps;
    @XmlAttribute(name = "wallthck")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String wallthck;
    @XmlAttribute(name = "width")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String width;
    @XmlAttribute(name = "distbet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String distbet;
    @XmlAttribute(name = "distconn")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String distconn;
    @XmlAttribute(name = "distlong")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String distlong;
    @XmlAttribute(name = "tubeconv")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tubeconv;
    @XmlAttribute(name = "tubeslit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tubeslit;
    @XmlAttribute(name = "tubefactor")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tubefactor;
    @XmlAttribute(name = "tubefactort")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tubefactort;
    @XmlAttribute(name = "calc_method")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String calcMethod;
    @XmlAttribute(name = "prog_module")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String progModule;
    @XmlAttribute(name = "user_module")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String userModule;
    @XmlAttribute(name = "module_from")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String moduleFrom;
    @XmlAttribute(name = "join_number")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String joinNumber;
    @XmlAttribute(name = "assem_item")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String assemItem;
    @XmlAttribute(name = "turnsbrk")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String turnsbrk;
    @XmlAttribute(name = "turnsbra")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String turnsbra;
    @XmlAttribute(name = "insulatedlength")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String insulatedlength;
    @XmlAttribute(name = "insulationlength")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String insulationlength;
    @XmlAttribute(name = "partdesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String partdesc;
    @XmlAttribute(name = "colordesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String colordesc;
    @XmlAttribute(name = "unitofmeasure")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String unitofmeasure;
    @XmlAttribute(name = "matcodedesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String matcodedesc;
    @XmlAttribute(name = "typecodedesc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String typecodedesc;
    @XmlAttribute(name = "groupname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String groupname;

    /**
     * Gets the value of the lengthu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthu() {
        return lengthu;
    }

    /**
     * Sets the value of the lengthu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthu(String value) {
        this.lengthu = value;
    }

    /**
     * Gets the value of the libraryref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibraryref() {
        return libraryref;
    }

    /**
     * Sets the value of the libraryref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibraryref(String value) {
        this.libraryref = value;
    }

    /**
     * Gets the value of the partnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * Sets the value of the partnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnumber(String value) {
        this.partnumber = value;
    }

    /**
     * Gets the value of the partrevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartrevision() {
        return partrevision;
    }

    /**
     * Sets the value of the partrevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartrevision(String value) {
        this.partrevision = value;
    }

    /**
     * Gets the value of the customerpartnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerpartnumber() {
        return customerpartnumber;
    }

    /**
     * Sets the value of the customerpartnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerpartnumber(String value) {
        this.customerpartnumber = value;
    }

    /**
     * Gets the value of the customername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * Sets the value of the customername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomername(String value) {
        this.customername = value;
    }

    /**
     * Gets the value of the supplierpartnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierpartnumber() {
        return supplierpartnumber;
    }

    /**
     * Sets the value of the supplierpartnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierpartnumber(String value) {
        this.supplierpartnumber = value;
    }

    /**
     * Gets the value of the suppliername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * Sets the value of the suppliername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppliername(String value) {
        this.suppliername = value;
    }

    /**
     * Gets the value of the layer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayer() {
        return layer;
    }

    /**
     * Sets the value of the layer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayer(String value) {
        this.layer = value;
    }

    /**
     * Gets the value of the instype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstype() {
        return instype;
    }

    /**
     * Sets the value of the instype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstype(String value) {
        this.instype = value;
    }

    /**
     * Gets the value of the typecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * Sets the value of the typecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypecode(String value) {
        this.typecode = value;
    }

    /**
     * Gets the value of the colorcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorcode() {
        return colorcode;
    }

    /**
     * Sets the value of the colorcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorcode(String value) {
        this.colorcode = value;
    }

    /**
     * Gets the value of the materialcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialcode() {
        return materialcode;
    }

    /**
     * Sets the value of the materialcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialcode(String value) {
        this.materialcode = value;
    }

    /**
     * Gets the value of the cutback property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCutback() {
        return cutback;
    }

    /**
     * Sets the value of the cutback property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCutback(String value) {
        this.cutback = value;
    }

    /**
     * Gets the value of the overlaps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverlaps() {
        return overlaps;
    }

    /**
     * Sets the value of the overlaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverlaps(String value) {
        this.overlaps = value;
    }

    /**
     * Gets the value of the wallthck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWallthck() {
        return wallthck;
    }

    /**
     * Sets the value of the wallthck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWallthck(String value) {
        this.wallthck = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

    /**
     * Gets the value of the distbet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistbet() {
        return distbet;
    }

    /**
     * Sets the value of the distbet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistbet(String value) {
        this.distbet = value;
    }

    /**
     * Gets the value of the distconn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistconn() {
        return distconn;
    }

    /**
     * Sets the value of the distconn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistconn(String value) {
        this.distconn = value;
    }

    /**
     * Gets the value of the distlong property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistlong() {
        return distlong;
    }

    /**
     * Sets the value of the distlong property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistlong(String value) {
        this.distlong = value;
    }

    /**
     * Gets the value of the tubeconv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubeconv() {
        if (tubeconv == null) {
            return "0";
        } else {
            return tubeconv;
        }
    }

    /**
     * Sets the value of the tubeconv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubeconv(String value) {
        this.tubeconv = value;
    }

    /**
     * Gets the value of the tubeslit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubeslit() {
        if (tubeslit == null) {
            return "0";
        } else {
            return tubeslit;
        }
    }

    /**
     * Sets the value of the tubeslit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubeslit(String value) {
        this.tubeslit = value;
    }

    /**
     * Gets the value of the tubefactor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubefactor() {
        return tubefactor;
    }

    /**
     * Sets the value of the tubefactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubefactor(String value) {
        this.tubefactor = value;
    }

    /**
     * Gets the value of the tubefactort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTubefactort() {
        return tubefactort;
    }

    /**
     * Sets the value of the tubefactort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTubefactort(String value) {
        this.tubefactort = value;
    }

    /**
     * Gets the value of the calcMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalcMethod() {
        return calcMethod;
    }

    /**
     * Sets the value of the calcMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalcMethod(String value) {
        this.calcMethod = value;
    }

    /**
     * Gets the value of the progModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgModule() {
        return progModule;
    }

    /**
     * Sets the value of the progModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgModule(String value) {
        this.progModule = value;
    }

    /**
     * Gets the value of the userModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserModule() {
        return userModule;
    }

    /**
     * Sets the value of the userModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserModule(String value) {
        this.userModule = value;
    }

    /**
     * Gets the value of the moduleFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModuleFrom() {
        return moduleFrom;
    }

    /**
     * Sets the value of the moduleFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModuleFrom(String value) {
        this.moduleFrom = value;
    }

    /**
     * Gets the value of the joinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinNumber() {
        return joinNumber;
    }

    /**
     * Sets the value of the joinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinNumber(String value) {
        this.joinNumber = value;
    }

    /**
     * Gets the value of the assemItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssemItem() {
        return assemItem;
    }

    /**
     * Sets the value of the assemItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssemItem(String value) {
        this.assemItem = value;
    }

    /**
     * Gets the value of the turnsbrk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurnsbrk() {
        return turnsbrk;
    }

    /**
     * Sets the value of the turnsbrk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurnsbrk(String value) {
        this.turnsbrk = value;
    }

    /**
     * Gets the value of the turnsbra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurnsbra() {
        return turnsbra;
    }

    /**
     * Sets the value of the turnsbra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurnsbra(String value) {
        this.turnsbra = value;
    }

    /**
     * Gets the value of the insulatedlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsulatedlength() {
        return insulatedlength;
    }

    /**
     * Sets the value of the insulatedlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsulatedlength(String value) {
        this.insulatedlength = value;
    }

    /**
     * Gets the value of the insulationlength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsulationlength() {
        return insulationlength;
    }

    /**
     * Sets the value of the insulationlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsulationlength(String value) {
        this.insulationlength = value;
    }

    /**
     * Gets the value of the partdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartdesc() {
        return partdesc;
    }

    /**
     * Sets the value of the partdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartdesc(String value) {
        this.partdesc = value;
    }

    /**
     * Gets the value of the colordesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColordesc() {
        return colordesc;
    }

    /**
     * Sets the value of the colordesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColordesc(String value) {
        this.colordesc = value;
    }

    /**
     * Gets the value of the unitofmeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitofmeasure() {
        return unitofmeasure;
    }

    /**
     * Sets the value of the unitofmeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitofmeasure(String value) {
        this.unitofmeasure = value;
    }

    /**
     * Gets the value of the matcodedesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatcodedesc() {
        return matcodedesc;
    }

    /**
     * Sets the value of the matcodedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatcodedesc(String value) {
        this.matcodedesc = value;
    }

    /**
     * Gets the value of the typecodedesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypecodedesc() {
        return typecodedesc;
    }

    /**
     * Sets the value of the typecodedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypecodedesc(String value) {
        this.typecodedesc = value;
    }

    /**
     * Gets the value of the groupname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * Sets the value of the groupname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupname(String value) {
        this.groupname = value;
    }

}
