//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "operationpostfiltercondition")
public class Operationpostfiltercondition {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "match", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String match;
    @XmlAttribute(name = "queryname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String queryname;
    @XmlAttribute(name = "querytype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String querytype;
    @XmlAttribute(name = "filtertype")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String filtertype;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatch() {
        return match;
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatch(String value) {
        this.match = value;
    }

    /**
     * Gets the value of the queryname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryname() {
        return queryname;
    }

    /**
     * Sets the value of the queryname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryname(String value) {
        this.queryname = value;
    }

    /**
     * Gets the value of the querytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuerytype() {
        return querytype;
    }

    /**
     * Sets the value of the querytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuerytype(String value) {
        this.querytype = value;
    }

    /**
     * Gets the value of the filtertype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiltertype() {
        return filtertype;
    }

    /**
     * Sets the value of the filtertype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiltertype(String value) {
        this.filtertype = value;
    }

}
