//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "position")
public class Position {

    @XmlAttribute(name = "quadrant", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String quadrant;
    @XmlAttribute(name = "hjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hjust;
    @XmlAttribute(name = "vjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String vjust;
    @XmlAttribute(name = "nominaloriginuid")
    @XmlIDREF
    protected Object nominaloriginuid;
    @XmlAttribute(name = "nominaloriginref")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String nominaloriginref;
    @XmlAttribute(name = "nominalorigintype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nominalorigintype;
    @XmlAttribute(name = "originhjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originhjust;
    @XmlAttribute(name = "originvjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originvjust;
    @XmlAttribute(name = "hoffset")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hoffset;
    @XmlAttribute(name = "voffset")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String voffset;
    @XmlAttribute(name = "originpropertyname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String originpropertyname;
    @XmlAttribute(name = "replaceoriginproperty")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String replaceoriginproperty;
    @XmlAttribute(name = "leaderlineoriginhjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String leaderlineoriginhjust;
    @XmlAttribute(name = "leaderlineoriginvjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String leaderlineoriginvjust;
    @XmlAttribute(name = "leaderlinedecorationhjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String leaderlinedecorationhjust;
    @XmlAttribute(name = "leaderlinedecorationvjust")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String leaderlinedecorationvjust;
    @XmlAttribute(name = "underlineside")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String underlineside;
    @XmlAttribute(name = "underlineoffset")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String underlineoffset;
    @XmlAttribute(name = "ispositionlocked")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ispositionlocked;
    @XmlAttribute(name = "usenominalsymbolorigin")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String usenominalsymbolorigin;
    @XmlAttribute(name = "usefirstframe")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String usefirstframe;

    /**
     * Gets the value of the quadrant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuadrant() {
        return quadrant;
    }

    /**
     * Sets the value of the quadrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuadrant(String value) {
        this.quadrant = value;
    }

    /**
     * Gets the value of the hjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHjust() {
        return hjust;
    }

    /**
     * Sets the value of the hjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHjust(String value) {
        this.hjust = value;
    }

    /**
     * Gets the value of the vjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVjust() {
        return vjust;
    }

    /**
     * Sets the value of the vjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVjust(String value) {
        this.vjust = value;
    }

    /**
     * Gets the value of the nominaloriginuid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNominaloriginuid() {
        return nominaloriginuid;
    }

    /**
     * Sets the value of the nominaloriginuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNominaloriginuid(Object value) {
        this.nominaloriginuid = value;
    }

    /**
     * Gets the value of the nominaloriginref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominaloriginref() {
        return nominaloriginref;
    }

    /**
     * Sets the value of the nominaloriginref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominaloriginref(String value) {
        this.nominaloriginref = value;
    }

    /**
     * Gets the value of the nominalorigintype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNominalorigintype() {
        return nominalorigintype;
    }

    /**
     * Sets the value of the nominalorigintype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNominalorigintype(String value) {
        this.nominalorigintype = value;
    }

    /**
     * Gets the value of the originhjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginhjust() {
        return originhjust;
    }

    /**
     * Sets the value of the originhjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginhjust(String value) {
        this.originhjust = value;
    }

    /**
     * Gets the value of the originvjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginvjust() {
        return originvjust;
    }

    /**
     * Sets the value of the originvjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginvjust(String value) {
        this.originvjust = value;
    }

    /**
     * Gets the value of the hoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoffset() {
        return hoffset;
    }

    /**
     * Sets the value of the hoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoffset(String value) {
        this.hoffset = value;
    }

    /**
     * Gets the value of the voffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoffset() {
        return voffset;
    }

    /**
     * Sets the value of the voffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoffset(String value) {
        this.voffset = value;
    }

    /**
     * Gets the value of the originpropertyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginpropertyname() {
        return originpropertyname;
    }

    /**
     * Sets the value of the originpropertyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginpropertyname(String value) {
        this.originpropertyname = value;
    }

    /**
     * Gets the value of the replaceoriginproperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaceoriginproperty() {
        return replaceoriginproperty;
    }

    /**
     * Sets the value of the replaceoriginproperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaceoriginproperty(String value) {
        this.replaceoriginproperty = value;
    }

    /**
     * Gets the value of the leaderlineoriginhjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaderlineoriginhjust() {
        return leaderlineoriginhjust;
    }

    /**
     * Sets the value of the leaderlineoriginhjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaderlineoriginhjust(String value) {
        this.leaderlineoriginhjust = value;
    }

    /**
     * Gets the value of the leaderlineoriginvjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaderlineoriginvjust() {
        return leaderlineoriginvjust;
    }

    /**
     * Sets the value of the leaderlineoriginvjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaderlineoriginvjust(String value) {
        this.leaderlineoriginvjust = value;
    }

    /**
     * Gets the value of the leaderlinedecorationhjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaderlinedecorationhjust() {
        return leaderlinedecorationhjust;
    }

    /**
     * Sets the value of the leaderlinedecorationhjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaderlinedecorationhjust(String value) {
        this.leaderlinedecorationhjust = value;
    }

    /**
     * Gets the value of the leaderlinedecorationvjust property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaderlinedecorationvjust() {
        return leaderlinedecorationvjust;
    }

    /**
     * Sets the value of the leaderlinedecorationvjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaderlinedecorationvjust(String value) {
        this.leaderlinedecorationvjust = value;
    }

    /**
     * Gets the value of the underlineside property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlineside() {
        return underlineside;
    }

    /**
     * Sets the value of the underlineside property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlineside(String value) {
        this.underlineside = value;
    }

    /**
     * Gets the value of the underlineoffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnderlineoffset() {
        return underlineoffset;
    }

    /**
     * Sets the value of the underlineoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnderlineoffset(String value) {
        this.underlineoffset = value;
    }

    /**
     * Gets the value of the ispositionlocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIspositionlocked() {
        if (ispositionlocked == null) {
            return "false";
        } else {
            return ispositionlocked;
        }
    }

    /**
     * Sets the value of the ispositionlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIspositionlocked(String value) {
        this.ispositionlocked = value;
    }

    /**
     * Gets the value of the usenominalsymbolorigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsenominalsymbolorigin() {
        if (usenominalsymbolorigin == null) {
            return "false";
        } else {
            return usenominalsymbolorigin;
        }
    }

    /**
     * Sets the value of the usenominalsymbolorigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsenominalsymbolorigin(String value) {
        this.usenominalsymbolorigin = value;
    }

    /**
     * Gets the value of the usefirstframe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsefirstframe() {
        if (usefirstframe == null) {
            return "false";
        } else {
            return usefirstframe;
        }
    }

    /**
     * Sets the value of the usefirstframe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsefirstframe(String value) {
        this.usefirstframe = value;
    }

}
