//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.13 at 11:46:37 AM CST 
//


package com.mentor.capital.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stylingxreftextgfxdetails"
})
@XmlRootElement(name = "vportstylingxrefdetails")
public class Vportstylingxrefdetails {

    @XmlAttribute(name = "template")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String template;
    @XmlAttribute(name = "linesperblock")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String linesperblock;
    @XmlAttribute(name = "referencesperline")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String referencesperline;
    @XmlAttribute(name = "delimiter")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String delimiter;
    @XmlAttribute(name = "firstblockx")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String firstblockx;
    @XmlAttribute(name = "firstblocky")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String firstblocky;
    @XmlAttribute(name = "decorationId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decorationId;
    @XmlAttribute(name = "decorationname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String decorationname;
    @XmlAttribute(name = "stylesetname")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String stylesetname;
    @XmlAttribute(name = "decorationvisible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String decorationvisible;
    protected Stylingxreftextgfxdetails stylingxreftextgfxdetails;

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the linesperblock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinesperblock() {
        if (linesperblock == null) {
            return "0";
        } else {
            return linesperblock;
        }
    }

    /**
     * Sets the value of the linesperblock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinesperblock(String value) {
        this.linesperblock = value;
    }

    /**
     * Gets the value of the referencesperline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencesperline() {
        if (referencesperline == null) {
            return "0";
        } else {
            return referencesperline;
        }
    }

    /**
     * Sets the value of the referencesperline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencesperline(String value) {
        this.referencesperline = value;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelimiter(String value) {
        this.delimiter = value;
    }

    /**
     * Gets the value of the firstblockx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstblockx() {
        return firstblockx;
    }

    /**
     * Sets the value of the firstblockx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstblockx(String value) {
        this.firstblockx = value;
    }

    /**
     * Gets the value of the firstblocky property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstblocky() {
        return firstblocky;
    }

    /**
     * Sets the value of the firstblocky property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstblocky(String value) {
        this.firstblocky = value;
    }

    /**
     * Gets the value of the decorationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecorationId() {
        return decorationId;
    }

    /**
     * Sets the value of the decorationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecorationId(String value) {
        this.decorationId = value;
    }

    /**
     * Gets the value of the decorationname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecorationname() {
        return decorationname;
    }

    /**
     * Sets the value of the decorationname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecorationname(String value) {
        this.decorationname = value;
    }

    /**
     * Gets the value of the stylesetname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStylesetname() {
        return stylesetname;
    }

    /**
     * Sets the value of the stylesetname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStylesetname(String value) {
        this.stylesetname = value;
    }

    /**
     * Gets the value of the decorationvisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecorationvisible() {
        return decorationvisible;
    }

    /**
     * Sets the value of the decorationvisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecorationvisible(String value) {
        this.decorationvisible = value;
    }

    /**
     * Gets the value of the stylingxreftextgfxdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Stylingxreftextgfxdetails }
     *     
     */
    public Stylingxreftextgfxdetails getStylingxreftextgfxdetails() {
        return stylingxreftextgfxdetails;
    }

    /**
     * Sets the value of the stylingxreftextgfxdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stylingxreftextgfxdetails }
     *     
     */
    public void setStylingxreftextgfxdetails(Stylingxreftextgfxdetails value) {
        this.stylingxreftextgfxdetails = value;
    }

}
