package com.esoon.capitaleasygo.action.capitallibraryhandle.util;

import com.acconsys.capital.lib.entity.AssemblyType;
import com.acconsys.capital.lib.entity.BackshellPlugType;
import com.acconsys.capital.lib.entity.BackshellSealType;
import com.acconsys.capital.lib.entity.BackshellType;
import com.acconsys.capital.lib.entity.CavityPlugType;
import com.acconsys.capital.lib.entity.CavitySealType;
import com.acconsys.capital.lib.entity.CavitygroupType;
import com.acconsys.capital.lib.entity.ChsuserpropertyType;
import com.acconsys.capital.lib.entity.ChsuserpropertytypeType;
import com.acconsys.capital.lib.entity.ClipType;
import com.acconsys.capital.lib.entity.ConnectorSealType;
import com.acconsys.capital.lib.entity.ConnectorType;
import com.acconsys.capital.lib.entity.CustomerorganisationType;
import com.acconsys.capital.lib.entity.DeviceType;
import com.acconsys.capital.lib.entity.FixtureType;
import com.acconsys.capital.lib.entity.GrommetType;
import com.acconsys.capital.lib.entity.HeatshrinkSleeveType;
import com.acconsys.capital.lib.entity.IdcconnectorType;
import com.acconsys.capital.lib.entity.InhouseAssemblyType;
import com.acconsys.capital.lib.entity.LibrarycolorType;
import com.acconsys.capital.lib.entity.LibrarycomponenttypeType;
import com.acconsys.capital.lib.entity.LibrarycustomercolcodeType;
import com.acconsys.capital.lib.entity.LibrarymaterialType;
import com.acconsys.capital.lib.entity.LibrarypitchType;
import com.acconsys.capital.lib.entity.LibraryrevisiongroupType;
import com.acconsys.capital.lib.entity.LibraryscopeType;
import com.acconsys.capital.lib.entity.LibrarywiregroupcodeType;
import com.acconsys.capital.lib.entity.LibrarywirepitchType;
import com.acconsys.capital.lib.entity.LibrarywirespecType;
import com.acconsys.capital.lib.entity.LibrarywirethicknessType;
import com.acconsys.capital.lib.entity.ManufacturingsiteorganisationType;
import com.acconsys.capital.lib.entity.MulticoreType;
import com.acconsys.capital.lib.entity.OtherType;
import com.acconsys.capital.lib.entity.SolderSleeveType;
import com.acconsys.capital.lib.entity.SpliceType;
import com.acconsys.capital.lib.entity.SupplierorganisationType;
import com.acconsys.capital.lib.entity.TapeType;
import com.acconsys.capital.lib.entity.TerminalType;
import com.acconsys.capital.lib.entity.TubeType;
import com.acconsys.capital.lib.entity.UltrasonicweldType;
import com.acconsys.capital.lib.entity.WireType;

public class LibrarySchemaConst {
	
	public static Class librarycolor = LibrarycolorType.class;
	public static Class librarymaterial = LibrarymaterialType.class;
	public static Class librarycomponenttype = LibrarycomponenttypeType.class;
	public static Class customerorganisation = CustomerorganisationType.class;
	public static Class manufacturingsiteorganisation = ManufacturingsiteorganisationType.class;
	public static Class supplierorganisation = SupplierorganisationType.class;
	public static Class librarywirespec = LibrarywirespecType.class;
	public static Class librarywirethickness = LibrarywirethicknessType.class;
	public static Class chsuserproperty = ChsuserpropertyType.class;
	public static Class chsuserpropertytype = ChsuserpropertytypeType.class;
	public static Class librarycustomercolcode = LibrarycustomercolcodeType.class;
	public static Class librarypitch = LibrarypitchType.class;
	public static Class librarywirepitch = LibrarywirepitchType.class;
	public static Class librarywiregroupcode = LibrarywiregroupcodeType.class;
	public static Class assemblypart = AssemblyType.class;
	public static Class backshellpart = BackshellType.class;
	public static Class backshellplugpart = BackshellPlugType.class;
	public static Class backshellsealpart = BackshellSealType.class;
	public static Class cavitygrouppart = CavitygroupType.class;
	public static Class cavityplugpart = CavityPlugType.class;
	public static Class cavitysealpart = CavitySealType.class;
	public static Class clippart = ClipType.class;
	public static Class connectorpart = ConnectorType.class;
	public static Class connectorsealpart = ConnectorSealType.class;
	public static Class devicepart = DeviceType.class;
	public static Class grommetpart = GrommetType.class;
	public static Class heatshrinksleevepart = HeatshrinkSleeveType.class;
	public static Class idcconnectorpart = IdcconnectorType.class;
	public static Class inhouseassemblypart = InhouseAssemblyType.class;
	public static Class multicorepart = MulticoreType.class;
	public static Class otherpart = OtherType.class;
	public static Class soldersleevepart = SolderSleeveType.class;
	public static Class splicepart = SpliceType.class;
	public static Class tapepart = TapeType.class;
	public static Class terminalpart = TerminalType.class;
	public static Class tubepart = TubeType.class;
	public static Class ultrasonicweldpart = UltrasonicweldType.class;
	public static Class wirepart = WireType.class;
	public static Class fixturepart = FixtureType.class;
	public static Class libraryrevisiongroup = LibraryrevisiongroupType.class;
	public static Class libraryscopecode = LibraryscopeType.class;
	public static String GROUP_NAME = "GroupName" ;
	public static String DESCRIPTION = "Description";
	public static String TYPE_CODE = "TypeCode";
	public static String MATERIAL_CODE = "MaterialCode";
	public static String INCLUDE_ON_BOM = "IncludeOnBom"; //stes
	public static String STATUS = "Status";//test
	public static String UNIT_OF_MEASURE = "UnitofMeasure";//单位
	public static String DOMAIN = "Domain";
	public static String REPLACE_BY = "ReplaceBy";
	public static String ALTERNATE = "Alternate";
	public static String WEIGHT = "Weight";
	public static String SPECIFICATION = "Specification";
	public static String USER_FILED1 = "UserFiled1";
	public static String USER_FILED2 = "UserFiled2";
	public static String USER_FILED3 = "UserFiled3";
	public static String USER_FILED4 = "UserFiled4";
	public static String USER_FILED5 = "UserFiled5";
	public static String PROPERTIES = "Properties";
	public static String SUPPLIER = "Supplier";
	public static String SUPPLIER_PART_NUMBER= "supplierPartNumber";
	public static String MATING = "Mating";
	public static String CAVITY_ATTRIBUTES="CavityAttributes";
	public static String NO_CAVITIES="NoCavities";
	public static String ADD_ON = "AddOn";
	public static String KNOCK_OFF = "KnockOff";
	public static String WIRE_SPECIFICATION = "WireSpecification";
	public static String CSA = "CSA";
	public static String COLOR_CODE="ColorCode";
	public static String OUTSIDE_DIAMETER_DEFINED="OutsideDiameterDefined";
	public static String OUTSIDE_DIAMETER_CALC ="OutsideDiameterCalc";
	public static String NO_TERMINATIONS="NoTerminations";
	public static String COLOR_Description = "ColorDescription" ; 
	public static String MATERIAL_DESCRIPTION = "MaterialDescription" ;
	public static String COMP_MODEL= "COMP_MODEL";
	public static String SUPPLIER_SPECIFICATION = "SupplierSpecification" ;
	public static String TYPE_DESCRIPTION = "TypeCodeDescription" ;
	public static String CONNECTOR = "Connector";
	public static String WIRE = "Wire" ;
	public static String TERMINAL = "Terminal" ;
	public static String OTHER = "Other";
	public static String BACKSHELL ="Backshell" ;
	
	
}
